menu:
  home: /
  archive: /archives
  about: /about

banner: /image/banner.jpg
avatar: /avatar.png
favicon: /favicon.ico
weixin: /weixin.jpg

social:
  github: https://github.com/DYSDF
  # twitter: http://twitter.com/littlewin_wang
  # weibo: http://weibo.com/fredinweibo
  envelope: mailto:admin@duan-ya.com
  rss: /atom.xml

# Comment
# e.g uyan: 2128137
uyan: 2128137

# Analytics
# google-analytics:
ga: UA-92791318-1

# Copyright Infomation
startyear: 2016

# Support hexo-renderer-scss
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false

# Resume related
resume:
